// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalcFederalTax(arg1:number,arg2:string):Promise<number>;

export function CalcFicaTax(arg1:number):Promise<number>;

export function CalcStateTax(arg1:number,arg2:string,arg3:string):Promise<number>;

export function GenerateInsights(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function WriteToJson(arg1:Record<string, Record<string, any>>):Promise<void>;
