// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalcFederalTax(arg1, arg2) {
  return window['go']['main']['App']['CalcFederalTax'](arg1, arg2);
}

export function CalcFicaTax(arg1) {
  return window['go']['main']['App']['CalcFicaTax'](arg1);
}

export function CalcStateTax(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalcStateTax'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function WriteToJson(arg1) {
  return window['go']['main']['App']['WriteToJson'](arg1);
}
